.\1brc_ti.exe -inputfile .\testdata\measurements-1mil.txt -processtype 0 > log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements-1mil.txt -processtype 1 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements-1mil.txt -processtype 2 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements-1mil.txt -processtype 3 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements-10mil.txt -processtype 0 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements-10mil.txt -processtype 1 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements-10mil.txt -processtype 2 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements-10mil.txt -processtype 3 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements-100mil.txt -processtype 0 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements-100mil.txt -processtype 1 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements-100mil.txt -processtype 2 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements-100mil.txt -processtype 3 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements.txt -processtype 0 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements.txt -processtype 1 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements.txt -processtype 2 >> log.txt -noprint
.\1brc_ti.exe -inputfile .\testdata\measurements.txt -processtype 3 >> log.txt -noprint
